name: coding standard
on:
  pull_request:
  push:
    branches:
      - main
      - '*.x'

jobs:
  coding-standard:
    name: PSR-12 coding standard
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install PHP code sniffer
        run: composer global require squizlabs/php_codesniffer

      - name: Check against PSR12 standard
        run: |
          `composer global config bin-dir --absolute --quiet`/phpcs --standard=PSR12 ./src
